name: meowstodon_lint
description: Custom meowstodon lint rules
version: 1.0.0
repository: https://github.com/abraham/meowstodon_lint

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^8.4.0
  analysis_server_plugin: ^0.3.3

dev_dependencies:
  analyzer_testing: ^0.1.0
  lints: ^6.0.0
  test: ^1.0.0
  test_reflective_loader: ">=0.2.0 <0.5.0"
